package com.example.data.repository

import android.util.Log
import com.example.data.model.EpisodeData
import com.example.data.model.Movie
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/**
 * Global Cloud Catalog Service for PrimePlex.
 * Synchronizes movies and series published by the admin to a shared cloud bin,
 * ensuring all users and devices (including Android TV / Google TV) receive new titles
 * instantly and retain them permanently across app updates and fresh installs.
 */
object CloudCatalogService {
    private const val TAG = "CloudCatalogService"
    
    // Persistent PrimePlex Shared Catalog Bin
    private const val CLOUD_BIN_URL = "https://extendsclass.com/api/json-storage/bin/affeded"

    private val client = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .writeTimeout(15, TimeUnit.SECONDS)
        .build()

    /**
     * Fetches all movies published to the global cloud catalog.
     */
    suspend fun fetchGlobalCatalog(): List<Movie> = withContext(Dispatchers.IO) {
        try {
            val request = Request.Builder()
                .url(CLOUD_BIN_URL)
                .header("Cache-Control", "no-cache")
                .get()
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    Log.w(TAG, "Failed to fetch cloud catalog: HTTP ${response.code}")
                    return@withContext emptyList()
                }

                val body = response.body?.string() ?: return@withContext emptyList()
                val json = JSONObject(body)
                val catalogArray = json.optJSONArray("catalog") ?: JSONArray()
                val movies = mutableListOf<Movie>()

                for (i in 0 until catalogArray.length()) {
                    val obj = catalogArray.optJSONObject(i) ?: continue
                    val title = obj.optString("title", "").trim()
                    if (title.isEmpty()) continue

                    val episodesJson = obj.optString("episodesJson", "")

                    movies.add(
                        Movie(
                            id = 0, // Auto-generated by Room
                            title = title,
                            description = obj.optString("description", "Sin sinopsis."),
                            videoUrl = obj.optString("videoUrl", "").trim(),
                            posterUrl = obj.optString("posterUrl", "").trim(),
                            category = obj.optString("category", "Películas"),
                            genre = obj.optString("genre", "Acción"),
                            year = obj.optString("year", "2026"),
                            duration = obj.optString("duration", "120 min"),
                            isFeatured = obj.optBoolean("isFeatured", false),
                            cast = obj.optString("cast", ""),
                            imdbRating = obj.optString("imdbRating", ""),
                            imdbId = obj.optString("imdbId", ""),
                            tmdbId = obj.optString("tmdbId", ""),
                            episodesJson = episodesJson,
                            metadataSource = obj.optString("metadataSource", "Nube PrimePlex")
                        )
                    )
                }

                Log.d(TAG, "Fetched ${movies.size} movies from global cloud catalog.")
                return@withContext movies
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error fetching global cloud catalog: ${e.message}", e)
            return@withContext emptyList()
        }
    }

    /**
     * Publishes a newly added movie or series to the shared cloud catalog
     * so that all other users and devices see it automatically.
     */
    suspend fun publishMovieToCloud(movie: Movie): Boolean = withContext(Dispatchers.IO) {
        try {
            // 1. Fetch current global list to avoid overwriting existing movies
            val currentList = fetchGlobalCatalog().toMutableList()

            // Check if already present by title and year
            val existingIndex = currentList.indexOfFirst {
                it.title.equals(movie.title, ignoreCase = true) &&
                        (it.year == movie.year || it.videoUrl == movie.videoUrl)
            }

            if (existingIndex >= 0) {
                currentList[existingIndex] = movie
            } else {
                currentList.add(movie)
            }

            // 2. Prepare payload
            val catalogArray = JSONArray()
            for (m in currentList) {
                val itemObj = JSONObject().apply {
                    put("title", m.title)
                    put("description", m.description)
                    put("videoUrl", m.videoUrl)
                    put("posterUrl", m.posterUrl)
                    put("category", m.category)
                    put("genre", m.genre)
                    put("year", m.year)
                    put("duration", m.duration)
                    put("isFeatured", m.isFeatured)
                    put("cast", m.cast)
                    put("imdbRating", m.imdbRating)
                    put("imdbId", m.imdbId)
                    put("tmdbId", m.tmdbId)
                    put("episodesJson", m.episodesJson)
                    put("metadataSource", m.metadataSource)
                }
                catalogArray.put(itemObj)
            }

            val payloadObj = JSONObject().apply {
                put("version", 1)
                put("catalog", catalogArray)
            }

            val requestBody = payloadObj.toString().toRequestBody("application/json; charset=utf-8".toMediaType())
            val request = Request.Builder()
                .url(CLOUD_BIN_URL)
                .put(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                val success = response.isSuccessful
                Log.d(TAG, "Published movie '${movie.title}' to cloud. Success: $success")
                return@withContext success
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error publishing movie to cloud: ${e.message}", e)
            return@withContext false
        }
    }

    /**
     * Permanently deletes a movie or series from the shared cloud catalog,
     * ensuring it never re-appears when closing and reopening the application.
     */
    suspend fun deleteMovieFromCloud(title: String, year: String = "", videoUrl: String = ""): Boolean = withContext(Dispatchers.IO) {
        try {
            val currentList = fetchGlobalCatalog().toMutableList()
            val beforeCount = currentList.size

            val trimmedTitle = title.trim()
            currentList.removeAll { m ->
                val titleMatch = m.title.trim().equals(trimmedTitle, ignoreCase = true)
                val yearMatch = year.isBlank() || m.year.trim() == year.trim()
                val urlMatch = videoUrl.isBlank() || m.videoUrl.trim() == videoUrl.trim()
                titleMatch && (yearMatch || urlMatch || year.isBlank())
            }

            if (currentList.size == beforeCount) {
                Log.d(TAG, "Movie '$title' was not present in cloud catalog.")
                return@withContext true
            }

            val catalogArray = JSONArray()
            for (m in currentList) {
                val itemObj = JSONObject().apply {
                    put("title", m.title)
                    put("description", m.description)
                    put("videoUrl", m.videoUrl)
                    put("posterUrl", m.posterUrl)
                    put("category", m.category)
                    put("genre", m.genre)
                    put("year", m.year)
                    put("duration", m.duration)
                    put("isFeatured", m.isFeatured)
                    put("cast", m.cast)
                    put("imdbRating", m.imdbRating)
                    put("imdbId", m.imdbId)
                    put("tmdbId", m.tmdbId)
                    put("episodesJson", m.episodesJson)
                    put("metadataSource", m.metadataSource)
                }
                catalogArray.put(itemObj)
            }

            val payloadObj = JSONObject().apply {
                put("version", 1)
                put("catalog", catalogArray)
            }

            val requestBody = payloadObj.toString().toRequestBody("application/json; charset=utf-8".toMediaType())
            val request = Request.Builder()
                .url(CLOUD_BIN_URL)
                .put(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                val success = response.isSuccessful
                Log.d(TAG, "Permanently deleted '$title' from cloud catalog. Success: $success")
                return@withContext success
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error deleting movie from cloud catalog: ${e.message}", e)
            return@withContext false
        }
    }
}
